[package]
name = "spot-client"
version = "0.1.0"
authors = ["teovoinea <voinea.teodor@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0.27"
bincode = "1.0.0"

[dependencies.stdweb]

git = "https://github.com/koute/stdweb.git"
